from PyQt5 import QtGui, QtWidgets, QtCore

from diploma.Data import DataApp


class Ui_chosing_of_border(object):
    def setupUi(self, chosing_of_border):
        self.global_data = DataApp
        chosing_of_border.setObjectName("GenethicAlgorythm")
        chosing_of_border.resize(812, 398)
        font = QtGui.QFont()
        font.setPointSize(8)
        chosing_of_border.setFont(font)
        self.centralwidget = QtWidgets.QWidget(chosing_of_border)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 300, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 10, 411, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Regular")
        font.setPointSize(22)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label.setWordWrap(True)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(445, 5, 391, 341))
        font = QtGui.QFont()
        font.setPointSize(self.global_data.data['ui_matrix_size'])
        font1 = QtGui.QFont()
        font1.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 300, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 300, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 300, 101, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 10, 40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setFont(font1)
        # self.pushButton_5.setStyleSheet("border-image: url(../diploma/experiments_results/back2.jpg) stretch;");
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(460, -10, 20, 381))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 421, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        chosing_of_border.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(chosing_of_border)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 26))
        self.menubar.setObjectName("menubar")
        chosing_of_border.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(chosing_of_border)
        # self.statusbar.setObjectName("statusbar")
        # chosing_of_border.setStatusBar(self.statusbar)

        self.retranslateUi(chosing_of_border)
        QtCore.QMetaObject.connectSlotsByName(chosing_of_border)

    def retranslateUi(self, chosing_of_border):
        _translate = QtCore.QCoreApplication.translate
        chosing_of_border.setWindowTitle(_translate("chosing_of_border", "chosing_of_border"))
        self.pushButton.setText(_translate("chosing_of_border", "По центру"))
        self.label.setText(_translate("chosing_of_border", "Способы формирования генов"))
        self.label_2.setText(_translate("chosing_of_border", f"{self.global_data.data['matrix']}"))
        self.pushButton_2.setText(_translate("chosing_of_border", "Слева"))
        self.pushButton_3.setText(_translate("chosing_of_border", "Справа"))
        self.pushButton_4.setText(_translate("chosing_of_border", "Рандомно"))
        self.pushButton_5.setText(_translate("chosing_of_border", "<"))
        self.label_3.setText(_translate("chosing_of_border", "Относительно левой и правой границы в процессоре"))
