from PyQt5 import QtGui, QtWidgets, QtCore


from diploma.Data import DataApp


class Ui_chose_of_one_or_all_methods(object):
    def setupUi(self, chose_of_one_or_all_methods):
        self.global_data = DataApp
        chose_of_one_or_all_methods.setObjectName("GenethicAlgorythm")
        chose_of_one_or_all_methods.resize(812, 398)
        font = QtGui.QFont()
        font.setPointSize(8)
        chose_of_one_or_all_methods.setFont(font)
        self.centralwidget = QtWidgets.QWidget(chose_of_one_or_all_methods)
        self.centralwidget.setObjectName("centralwidget")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(410, -50, 20, 411))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 300, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 300, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 300, 121, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 10, 401, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Regular")
        font.setPointSize(22)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(414, 5, 391, 341))
        font = QtGui.QFont()
        font.setPointSize(self.global_data.data['ui_matrix_size'])
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        chose_of_one_or_all_methods.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(chose_of_one_or_all_methods)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 26))
        self.menubar.setObjectName("menubar")
        chose_of_one_or_all_methods.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(chose_of_one_or_all_methods)
        # self.statusbar.setObjectName("statusbar")
        # chose_of_one_or_all_methods.setStatusBar(self.statusbar)

        self.retranslateUi(chose_of_one_or_all_methods)
        QtCore.QMetaObject.connectSlotsByName(chose_of_one_or_all_methods)

    def retranslateUi(self, chose_of_one_or_all_methods):
        _translate = QtCore.QCoreApplication.translate
        chose_of_one_or_all_methods.setWindowTitle(
            _translate("chose_of_one_or_all_methods", "chose_of_one_or_all_methods"))
        self.pushButton.setText(_translate("chose_of_one_or_all_methods", "Все методы"))
        self.pushButton_2.setText(_translate("chose_of_one_or_all_methods", "Конкретный метод"))
        self.pushButton_3.setText(_translate("chose_of_one_or_all_methods", "Вернуться"))
        self.label.setText(_translate("chose_of_one_or_all_methods",
                                      "Выбрать все или конкретный метод формирования (разбиения) начального поколения"))
        self.label_2.setText(_translate("chose_of_one_or_all_methods", f"{self.global_data.data['matrix']}"))