from PyQt5 import QtGui, QtWidgets, QtCore

from diploma.Data import DataApp


class Ui_formation_partitioning(object):
    def setupUi(self, formation_partitioning):
        self.global_data = DataApp()
        formation_partitioning.setObjectName("formation_partitioning")
        formation_partitioning.resize(812, 398)
        font = QtGui.QFont()
        font.setPointSize(8)
        formation_partitioning.setFont(font)
        self.centralwidget = QtWidgets.QWidget(formation_partitioning)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 471, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Regular")
        font.setPointSize(22)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label.setWordWrap(True)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(414, 5, 391, 341))
        font = QtGui.QFont()
        font.setPointSize(self.global_data.data['ui_matrix_size'])
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(460, -10, 20, 381))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(20, 180, 271, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 210, 271, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 240, 271, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 270, 251, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(125, 320, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(245, 320, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        formation_partitioning.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(formation_partitioning)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 26))
        self.menubar.setObjectName("menubar")
        formation_partitioning.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(formation_partitioning)
        # self.statusbar.setObjectName("statusbar")
        # formation_partitioning.setStatusBar(self.statusbar)

        self.retranslateUi(formation_partitioning)
        QtCore.QMetaObject.connectSlotsByName(formation_partitioning)

    def retranslateUi(self, GenethicAlgorythm):
        _translate = QtCore.QCoreApplication.translate
        GenethicAlgorythm.setWindowTitle(_translate("formation_partitioning", "formation_partitioning"))
        self.label.setText(_translate("formation_partitioning", "Способ формирования (разбиения) начального поколения"))
        self.label_2.setText(_translate("formation_partitioning", f"{self.global_data.data['matrix']}"))
        self.radioButton.setText(_translate("formation_partitioning", "50% Рандомно + 50% детерминированно"))
        self.radioButton_2.setText(_translate("formation_partitioning", "25% Рандомно + 75% детерминированно"))
        self.radioButton_3.setText(_translate("formation_partitioning", "75% Рандомно + 25% детерминированно"))
        self.radioButton_4.setText(_translate("formation_partitioning", "50% Плотников-Зверев + 50% Барьер"))
        self.pushButton.setText(_translate("formation_partitioning", "Дальше"))
        self.pushButton_2.setText(_translate("formation_partitioning", "Вернуться"))
