from PyQt5 import QtGui, QtWidgets, QtCore


class Ui_ga_loader(object):
    def setupUi(self, ga_loader):
        ga_loader.setObjectName("ga_loader")
        ga_loader.resize(822, 404)
        font = QtGui.QFont()
        font.setPointSize(9)
        font1 = QtGui.QFont()
        font1.setPointSize(11)
        ga_loader.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ga_loader)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 325, 161, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 10, 40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setFont(font1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(750, 10, 40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setFont(font1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(250, -5, 300, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Regular")
        font.setPointSize(22)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-20, 50, 1061, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 295, 781, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        # self.label_3 = QtWidgets.QLabel(self.centralwidget)
        # self.label_3.setGeometry(QtCore.QRect(21, 225, 80, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.label_3.setFont(font)
        # self.label_3.setAlignment(QtCore.Qt.AlignLeft)
        # self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 250, 735, 29))
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("background-color: black; color: lightgreen")
        # self.label_4 = QtWidgets.QLabel(self.centralwidget)
        # self.label_4.setGeometry(QtCore.QRect(20, 190, 735, 29))
        # self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 735, 29))
        self.label_5.setObjectName("label_2")
        self.label_5.setStyleSheet("background-color: black; color: lightgreen")
        self.label_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 190, 735, 29))
        self.label_6.setObjectName("label_2")
        self.label_6.setStyleSheet("background-color: black; color: lightgreen")
        self.label_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 160, 735, 29))
        self.label_7.setObjectName("label_2")
        self.label_7.setStyleSheet("background-color: black; color: lightgreen")
        ga_loader.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ga_loader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 26))
        self.menubar.setObjectName("menubar")
        ga_loader.setMenuBar(self.menubar)

        self.retranslateUi(ga_loader)
        QtCore.QMetaObject.connectSlotsByName(ga_loader)

    def retranslateUi(self, ga_loader):
        _translate = QtCore.QCoreApplication.translate
        ga_loader.setWindowTitle(_translate("ga_loader", "ga_loader"))
        self.pushButton.setText(_translate("ga_loader", "Cтарт"))
        self.pushButton_2.setText(_translate("ga_loader", "<"))
        self.pushButton_3.setText(_translate("ga_loader", ">"))
        self.label.setText(_translate("ga_loader", "Генетический Алгоритм"))
        # self.label_3.setText(_translate("ga_loader", f""))
        # self.label_4.setText(_translate("ga_loader", f""))
        self.label_2.setPlainText(_translate("ga_loader", 'Нажмите "Старт", чтобы запустить алгоритм'))
