from PyQt5 import QtGui, QtWidgets, QtCore


class Ui_generate_matrix_window(object):
    def setupUi(self, generate_matrix):
        generate_matrix.setObjectName("generate_matrix")
        generate_matrix.resize(812, 398)
        font = QtGui.QFont()
        font.setPointSize(8)
        generate_matrix.setFont(font)
        self.centralwidget = QtWidgets.QWidget(generate_matrix)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 300, 120, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 300, 120, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 300, 120, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(30, 10, 401, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Regular")
        font.setPointSize(22)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(414, 5, 391, 341))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(460, -10, 20, 381))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        generate_matrix.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(generate_matrix)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 26))
        self.menubar.setObjectName("menubar")
        generate_matrix.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(generate_matrix)
        # self.statusbar.setObjectName("statusbar")
        # generate_matrix.setStatusBar(self.statusbar)

        self.retranslateUi(generate_matrix)
        QtCore.QMetaObject.connectSlotsByName(generate_matrix)

    def retranslateUi(self, generate_matrix):
        _translate = QtCore.QCoreApplication.translate
        generate_matrix.setWindowTitle(_translate("generate_matrix", "generate_matrix"))
        self.pushButton.setText(_translate("generate_matrix", "Готовый вариант"))
        self.pushButton_2.setText(_translate("generate_matrix", "Новая матрица"))
        self.pushButton_3.setText(_translate("generate_matrix", "Вернуться"))
        self.label.setText(_translate("generate_matrix", "Использовать готовую матрицу или сгенерировать новую?"))
