from PyQt5 import QtGui, QtWidgets, QtCore

from diploma.Data import DataApp


class Ui_number_of_repetitons(object):
    def setupUi(self, number_of_repetitons):
        self.global_data = DataApp()
        number_of_repetitons.setObjectName("number_of_repetitons")
        number_of_repetitons.resize(812, 398)
        font = QtGui.QFont()
        font.setPointSize(8)
        number_of_repetitons.setFont(font)
        self.centralwidget = QtWidgets.QWidget(number_of_repetitons)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 10, 401, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Regular")
        font.setPointSize(22)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-50, 300, 901, 121))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(414, 5, 391, 341))
        font = QtGui.QFont()
        font.setPointSize(self.global_data.data["ui_matrix_size"])
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(410, -50, 20, 411))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 240, 61, 21))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        number_of_repetitons.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(number_of_repetitons)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 26))
        self.menubar.setObjectName("menubar")
        number_of_repetitons.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(number_of_repetitons)
        # self.statusbar.setObjectName("statusbar")
        # number_of_repetitons.setStatusBar(self.statusbar)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(85, 310, 101, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton_2.setFont(font1)
        # self.pushButton_2.setWindowIcon(QtGui.QIcon('../diploma/experiments_results/back1.png'))
        # self.pushButton_2.setIconSize(QSize(101, 28))
        self.pushButton_2.setGeometry(QtCore.QRect(215, 310, 101, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(number_of_repetitons)
        QtCore.QMetaObject.connectSlotsByName(number_of_repetitons)

    def retranslateUi(self, number_of_repetitons):
        _translate = QtCore.QCoreApplication.translate
        number_of_repetitons.setWindowTitle(_translate("number_of_repetitons", "NumberOfRepeats"))
        self.label.setText(_translate("number_of_repetitons", "Задайте количество повторов генетического алгоритма"))
        self.label_2.setText(_translate("number_of_repetitons", f"{self.global_data.data['matrix']}"))
        self.pushButton.setText(_translate("number_of_repetitions", "Далее"))
        self.pushButton_2.setText(_translate("number_of_repetitions", "Вернуться"))
        self.lineEdit.setText(_translate("number_of_repetitons", "100"))