# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1152, 599)
        MainWindow.setStyleSheet("\n"
".QSpinBox\n"
"{\n"
"    color:white;    \n"
"    padding: 4px;\n"
"}\n"
"\n"
"\n"
".QLabel\n"
"{\n"
"    border: 1px solid red;\n"
"}\n"
"                                 \n"
"\n"
"\n"
"QWidget\n"
"{\n"
"    background-color: black;\n"
"    color: white;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: black;\n"
"    color: white;\n"
"    border-color: #000000;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #ffaf5d;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #dd872f;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"    background-color: #ff9c2b;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    padding: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::hover\n"
"{\n"
"    background-color: #ffaf5d;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::pressed\n"
"{\n"
"    background-color: #dd872f;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #38394e;\n"
"    color: white;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #4a4c68;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTableView-----*/\n"
"QTableView, \n"
"QHeaderView, \n"
"QTableView::item \n"
"{\n"
"    background-color: #232430;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected \n"
"{ \n"
"    background-color: #41424e;\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:horizontal \n"
"{\n"
"    background-color: #232430;\n"
"    border: 1px solid #37384d;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::indicator{\n"
"    background-color: #1d1d28;\n"
"    border: 1px solid #37384d;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::indicator:checked{\n"
"    image:url(\"./ressources/check.png\"); /*To replace*/\n"
"    background-color: #1d1d28;\n"
"\n"
"}\n"
"\n"
"/*-----QTabWidget-----*/\n"
"QTabWidget::pane \n"
"{ \n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabWidget::tab-bar \n"
"{\n"
"    left: 5px; \n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab \n"
"{\n"
"    color: white;\n"
"    min-width: 1px;\n"
"    padding-left: 25px;\n"
"    margin-left:-22px;\n"
"    height: 28px;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected \n"
"{\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    height: 28px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!first \n"
"{\n"
"    margin-left: -20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:hover \n"
"{\n"
"    color: #DDD;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    border: none;\n"
"    min-width: 100px;\n"
"    background-color: #56576c;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, \n"
"QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal \n"
"{\n"
"    width: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"{\n"
"    background-color: transparent;\n"
"    width: 8px;\n"
"    margin: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    border: none;\n"
"    min-height: 100px;\n"
"    background-color: #56576c;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical \n"
"{\n"
"    height: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"QCalendarWidget\n"
"{\n"
"     border: 5px solid red;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: white;\n"
"    border: 1px solid grey;\n"
"}\n"
"\n"
"QComboBox {\n"
"    color: white;\n"
"    border: 1px solid grey;\n"
"}\n"
"QRadioButton {\n"
"    color: white;\n"
"    border: 1px solid red;\n"
"}\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: white;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QCheckBox\n"
"{\n"
"    border: 1px solid red;\n"
"}\n"
"\n"
"QSpinBox\n"
"{\n"
"    border: 1px solid grey;\n"
"    height: 100%;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 560, 1131, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 491, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 60, 411, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 110, 411, 41))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 160, 411, 41))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 210, 411, 41))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 260, 491, 41))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 310, 411, 41))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 360, 411, 41))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(10, 410, 411, 41))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 460, 411, 41))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(10, 510, 411, 41))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(430, 60, 71, 41))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.plainTextEdit = QtWidgets.QSpinBox(self.verticalLayoutWidget_13)
        self.plainTextEdit.setMaximum(100000)
        self.plainTextEdit.setProperty("value", 10)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_13.addWidget(self.plainTextEdit)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(430, 110, 71, 41))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.plainTextEdit_1 = QtWidgets.QSpinBox(self.verticalLayoutWidget_14)
        self.plainTextEdit_1.setMaximum(100000)
        self.plainTextEdit_1.setProperty("value", 5)
        self.plainTextEdit_1.setObjectName("plainTextEdit_1")
        self.verticalLayout_14.addWidget(self.plainTextEdit_1)
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(430, 160, 71, 41))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.plainTextEdit_3 = QtWidgets.QSpinBox(self.verticalLayoutWidget_15)
        self.plainTextEdit_3.setMaximum(100000)
        self.plainTextEdit_3.setProperty("value", 20)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout_15.addWidget(self.plainTextEdit_3)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(430, 210, 71, 41))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.plainTextEdit_5 = QtWidgets.QSpinBox(self.verticalLayoutWidget_16)
        self.plainTextEdit_5.setMaximum(100000)
        self.plainTextEdit_5.setProperty("value", 50)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.verticalLayout_17.addWidget(self.plainTextEdit_5)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(430, 310, 71, 41))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.plainTextEdit_7 = QtWidgets.QSpinBox(self.verticalLayoutWidget_18)
        self.plainTextEdit_7.setMaximum(100000)
        self.plainTextEdit_7.setProperty("value", 100)
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.verticalLayout_19.addWidget(self.plainTextEdit_7)
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(430, 362, 71, 41))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.plainTextEdit_8 = QtWidgets.QSpinBox(self.verticalLayoutWidget_19)
        self.plainTextEdit_8.setMaximum(100000)
        self.plainTextEdit_8.setProperty("value", 30)
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.verticalLayout_20.addWidget(self.plainTextEdit_8)
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(430, 410, 71, 41))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.plainTextEdit_9 = QtWidgets.QSpinBox(self.verticalLayoutWidget_20)
        self.plainTextEdit_9.setMaximum(100000)
        self.plainTextEdit_9.setProperty("value", 99)
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.verticalLayout_21.addWidget(self.plainTextEdit_9)
        self.verticalLayoutWidget_21 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_21.setGeometry(QtCore.QRect(430, 460, 71, 41))
        self.verticalLayoutWidget_21.setObjectName("verticalLayoutWidget_21")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_21)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.plainTextEdit_10 = QtWidgets.QSpinBox(self.verticalLayoutWidget_21)
        self.plainTextEdit_10.setMaximum(100000)
        self.plainTextEdit_10.setProperty("value", 99)
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.verticalLayout_22.addWidget(self.plainTextEdit_10)
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(830, 90, 311, 132))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_17)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_18.addWidget(self.comboBox)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_18.addWidget(self.label_17)
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_17)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_18.addWidget(self.horizontalSlider)
        self.verticalLayoutWidget_26 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_26.setGeometry(QtCore.QRect(830, 10, 261, 41))
        self.verticalLayoutWidget_26.setObjectName("verticalLayoutWidget_26")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_26)
        self.verticalLayout_27.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_26)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_27.addWidget(self.label_14)
        self.verticalLayoutWidget_28 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_28.setGeometry(QtCore.QRect(830, 250, 311, 111))
        self.verticalLayoutWidget_28.setObjectName("verticalLayoutWidget_28")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_28)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.combo_box1 = QtWidgets.QComboBox(self.verticalLayoutWidget_28)
        self.combo_box1.setObjectName("combo_box1")
        self.combo_box1.addItem("")
        self.combo_box1.addItem("")
        self.combo_box1.addItem("")
        self.combo_box1.addItem("")
        self.verticalLayout_29.addWidget(self.combo_box1)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_28)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_29.addWidget(self.label_18)
        self.verticalLayoutWidget_27 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_27.setGeometry(QtCore.QRect(830, 370, 311, 181))
        self.verticalLayoutWidget_27.setObjectName("verticalLayoutWidget_27")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_27)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_27)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_28.addWidget(self.label_15)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_27)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_28.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_27)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_28.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_27)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_28.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_27)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_28.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_27)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_28.addWidget(self.radioButton_5)
        self.verticalLayoutWidget_29 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_29.setGeometry(QtCore.QRect(510, 380, 311, 141))
        self.verticalLayoutWidget_29.setObjectName("verticalLayoutWidget_29")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_29)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_29)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_30.addWidget(self.pushButton_4)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_29)
        self.checkBox.setStyleSheet("")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_30.addWidget(self.checkBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_29)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_30.addWidget(self.comboBox_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_29)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_30.addWidget(self.pushButton_3)
        self.verticalLayoutWidget_30 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_30.setGeometry(QtCore.QRect(830, 60, 311, 21))
        self.verticalLayoutWidget_30.setObjectName("verticalLayoutWidget_30")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_30)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_30)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_31.addWidget(self.label_19)
        self.verticalLayoutWidget_31 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_31.setGeometry(QtCore.QRect(830, 220, 311, 21))
        self.verticalLayoutWidget_31.setObjectName("verticalLayoutWidget_31")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_31)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_31)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_32.addWidget(self.label_20)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1100, 10, 41, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutWidget_32 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_32.setGeometry(QtCore.QRect(510, 530, 311, 21))
        self.verticalLayoutWidget_32.setObjectName("verticalLayoutWidget_32")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_32)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_32)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_25.addWidget(self.label_16)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(510, 10, 311, 361))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setStyleSheet("QTabBar::tab \n"
"{ \n"
"    height:10px; \n"
"    width: 100px;\n"
"    border: 1px solid white; \n"
"    margin: 0px;\n"
"    padding: 24px;\n"
"    border-radius: 4px;\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setMaximumSize(QtCore.QSize(321, 16777215))
        self.tab.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_24 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_24.setGeometry(QtCore.QRect(0, 0, 311, 301))
        self.verticalLayoutWidget_24.setObjectName("verticalLayoutWidget_24")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_24)
        self.verticalLayout_26.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.verticalLayoutWidget_24)
        self.scrollArea_2.setStyleSheet("QScrollArea\n"
"{\n"
"    border: 1px solid grey;\n"
"}")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 307, 297))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_26.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_23 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(0, 0, 311, 301))
        self.verticalLayoutWidget_23.setObjectName("verticalLayoutWidget_23")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_23)
        self.verticalLayout_24.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_23)
        self.scrollArea.setStyleSheet("QScrollArea\n"
"{\n"
"    border: 1px solid grey;\n"
"}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 307, 297))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_24.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayoutWidget_22 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_22.setGeometry(QtCore.QRect(430, 510, 71, 41))
        self.verticalLayoutWidget_22.setObjectName("verticalLayoutWidget_22")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.plainTextEdit_11 = QtWidgets.QSpinBox(self.verticalLayoutWidget_22)
        self.plainTextEdit_11.setMaximum(100000)
        self.plainTextEdit_11.setProperty("value", 100)
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")
        self.verticalLayout_23.addWidget(self.plainTextEdit_11)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Начать Генетический Алгоритм"))
        self.label.setText(_translate("MainWindow", "Переменные для матрицы"))
        self.label_2.setText(_translate("MainWindow", "Количество заданий (m)"))
        self.label_3.setText(_translate("MainWindow", "Количество процессоров (n)"))
        self.label_4.setText(_translate("MainWindow", "Левая граница задания (T1)"))
        self.label_5.setText(_translate("MainWindow", "Правая граница задания (T2)"))
        self.label_6.setText(_translate("MainWindow", "Переменные для генетического алгоритма"))
        self.label_7.setText(_translate("MainWindow", "Количество особей в поколении (z)"))
        self.label_8.setText(_translate("MainWindow", "Количество повторов для выхода из цикла (k)"))
        self.label_9.setText(_translate("MainWindow", "Вероятность кроссовера (Pk)"))
        self.label_10.setText(_translate("MainWindow", "Вероятность мутации(Pm)"))
        self.label_12.setText(_translate("MainWindow", "Количество сгенерированных матриц (r)"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Один метод"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Два метода"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Три метода"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Четыре метода"))
        self.label_17.setText(_translate("MainWindow", "/\\ \n"
"|\n"
"Выберите количество методов, чтоб создать\n"
" разбиение начального поколения"))
        self.label_14.setText(_translate("MainWindow", "Формирование начального\n"
"поколения"))
        self.combo_box1.setItemText(0, _translate("MainWindow", "Метод минимальных элементов"))
        self.combo_box1.setItemText(1, _translate("MainWindow", "Метод Плотникова-Зверева"))
        self.combo_box1.setItemText(2, _translate("MainWindow", "Метод Барьера"))
        self.combo_box1.setItemText(3, _translate("MainWindow", "Метод рандомного формирования"))
        self.label_18.setText(_translate("MainWindow", "Разбиение формируется от 2-х и более"))
        self.label_15.setText(_translate("MainWindow", "Методы расположения генов"))
        self.radioButton_2.setText(_translate("MainWindow", "По левой границе"))
        self.radioButton.setText(_translate("MainWindow", "По правой границе"))
        self.radioButton_3.setText(_translate("MainWindow", "По центральной границе"))
        self.radioButton_4.setText(_translate("MainWindow", "По рандомной границе"))
        self.radioButton_5.setText(_translate("MainWindow", "По всем границам"))
        self.pushButton_4.setText(_translate("MainWindow", "Рассмотреть подробнее"))
        self.checkBox.setText(_translate("MainWindow", "Генерировать матрицу при каждом\n"
"повторе"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Без сортировки"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Отсортированно по возрастанию"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Отсортированно по убыванию"))
        self.pushButton_3.setText(_translate("MainWindow", "Сгенерировать новые матрицы"))
        self.label_19.setText(_translate("MainWindow", "Методы разбиения"))
        self.label_20.setText(_translate("MainWindow", "Методы формирования"))
        self.pushButton_2.setText(_translate("MainWindow", ">"))
        self.label_16.setText(_translate("MainWindow", "Рябоконь Б.И. ©"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Матрицы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Результат"))
